version: '{build}'
image: Visual Studio 2017
configuration: Release
install:
- ps: .\Scripts\BeforeBuild.ps1
cache: C:\projects\pcman-windows\cache\vcpkg-installed
build:
  project: PCMan.sln
  parallel: true
  verbosity: minimal
after_build:
- ps: .\Scripts\AfterBuild.ps1
artifacts:
- path: Lite\Release\PCMan.7z
- path: Combo\Release\PCManCB.7z
- path: Release\PCMan.exe
- path: Release\PCManCB.exe
deploy:
  provider: GitHub
  auth_token: $(github_auth_token)
  draft: true
