version: '{build}'
image: Visual Studio 2017
configuration: Release
install:
- cmd: >-
    git clone -q --branch=master https://github.com/Microsoft/vcpkg.git vcpkg

    copy /y hack\portfile.cmake vcpkg\ports\libwebsockets\portfile.cmake

    pwd

    vcpkg\bootstrap-vcpkg.bat

    vcpkg\vcpkg integrate install

    vcpkg\vcpkg install libwebsockets

    pwd
- ps: >-
    [Net.ServicePointManager]::SecurityProtocol = 'Tls, Tls11, Tls12'

    Start-FileDownload 'https://curl.haxx.se/ca/cacert.pem'

    Copy-Item cacert.pem 'Combo\Debug\PCMan Combo\'

    Copy-Item cacert.pem 'Combo\Release\PCMan Combo\'

    Copy-Item cacert.pem 'Lite\Debug\PCMan\'

    Copy-Item cacert.pem 'Lite\Release\PCMan\'

cache: C:\projects\pcman-windows\vcpkg\installed
build:
  project: PCMan.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    cd Lite\Release

    7z a PCMan.7z PCMan
artifacts:
- path: Lite\Release\PCMan.7z
