version: '{build}'
image: Visual Studio 2017
configuration: Release
install:
- cmd: >-
    git clone -q --branch=master https://github.com/Microsoft/vcpkg.git vcpkg

    copy /y hack\portfile.cmake vcpkg\ports\libwebsockets\portfile.cmake

    pwd

    vcpkg\bootstrap-vcpkg.bat

    vcpkg\vcpkg integrate install

    vcpkg\vcpkg install libwebsockets

    pwd
cache: C:\projects\pcman-windows\vcpkg
build:
  project: PCMan.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    cd Lite\Release

    7z a Pcman.7z Pcman
artifacts:
- path: Lite\Release\Pcman.7z
